export const listingGeo = [
    {
        id: '1',
        name: 'Srikalahasteeswara Temple',
        description: 'A sacred Hindu temple dedicated to Lord Shiva, located in Srikalahasti, Andhra Pradesh, renowned for its ancient architecture and spiritual significance.',
        host: 'Srikalahasti Devasthanam',
        date: 'N/A',
        venue: 'Srikalahasti, Andhra Pradesh',
        price: 0,
        categories: ['Andhra Pradesh'],
        thumbnail_url: 'https://media.istockphoto.com/id/481962488/photo/waterpond-close-to-balaji-temple.jpg?s=612x612&w=0&k=20&c=P0SLeAYkRYaDY9C4R0DOGppxkMQ9xcIwu8AvVaSYPhU=',
        medium_url: 'https://media.istockphoto.com/id/481962488/photo/waterpond-close-to-balaji-temple.jpg?s=612x612&w=0&k=20&c=P0SLeAYkRYaDY9C4R0DOGppxkMQ9xcIwu8AvVaSYPhU=',
        latitude: '13.7492',
        longitude: '79.6992',
      },
      
    
    {
        id: '3',
        name: 'Golden Temple',
        description: 'A prominent Sikh Gurdwara located in Amritsar, Punjab, known for its golden dome and spiritual significance.',
        host: 'Shiromani Gurdwara Parbandhak Committee',
        date: 'N/A',
        venue: 'Amritsar, Punjab',
        price: 0,
        categories: ['Punjab'],
        thumbnail_url: 'https://example.com/images/golden-temple-thumb.jpg',
        medium_url: 'https://example.com/images/golden-temple-med.jpg',
        latitude: '31.6200',
        longitude: '74.8765',
      },
      {
        id: '4',
        name: 'Jagannath Temple',
        description: 'A major Hindu temple dedicated to Lord Jagannath in Puri, Odisha, known for its annual Rath Yatra festival.',
        host: 'Jagannath Temple Administration',
        date: 'N/A',
        venue: 'Puri, Odisha',
        price: 0,
        categories: ['Odisha'],
        thumbnail_url: 'https://example.com/images/jagannath-temple-thumb.jpg',
        medium_url: 'https://example.com/images/jagannath-temple-med.jpg',
        latitude: '19.8134',
        longitude: '85.8315',
      },
      {
        id: '5',
        name: 'Meenakshi Temple',
        description: 'A historic Hindu temple dedicated to Goddess Meenakshi and Lord Sundareswarar in Madurai, Tamil Nadu, known for its intricate architecture.',
        host: 'Meenakshi Amman Temple Trust',
        date: 'N/A',
        venue: 'Madurai, Tamil Nadu',
        price: 0,
        categories: ['Tamil Nadu'],
        thumbnail_url: 'https://example.com/images/meenakshi-temple-thumb.jpg',
        medium_url: 'https://example.com/images/meenakshi-temple-med.jpg',
        latitude: '9.9195',
        longitude: '78.1190',
      },
      {
        id: '6',
        name: 'Somnath Temple',
        description: 'An ancient Hindu temple located in Gujarat, believed to be the first among the twelve Jyotirlinga shrines of Lord Shiva.',
        host: 'Shree Somnath Trust',
        date: 'N/A',
        venue: 'Prabhas Patan, Gujarat',
        price: 0,
        categories: ['Gujarat'],
        thumbnail_url: 'https://example.com/images/somnath-temple-thumb.jpg',
        medium_url: 'https://example.com/images/somnath-temple-med.jpg',
        latitude: '20.8875',
        longitude: '70.4057',
      },
      {
        id: '7',
        name: 'Vaishno Devi Temple',
        description: 'A renowned Hindu temple dedicated to the manifestation of Goddess Vaishnavi, located in the Trikuta Mountains of Jammu and Kashmir.',
        host: 'Shri Mata Vaishno Devi Shrine Board',
        date: 'N/A',
        venue: 'Katra, Jammu and Kashmir',
        price: 0,
        categories: ['Jammu and Kashmir'],
        thumbnail_url: 'https://example.com/images/vaishno-devi-temple-thumb.jpg',
        medium_url: 'https://example.com/images/vaishno-devi-temple-med.jpg',
        latitude: '32.9728',
        longitude: '74.8974',
      },
      {
        id: '8',
        name: 'Kedarnath Temple',
        description: 'A Hindu temple dedicated to Lord Shiva, located in the Garhwal Himalayas of Uttarakhand, one of the Char Dham pilgrimage sites.',
        host: 'Kedarnath Temple Committee',
        date: 'N/A',
        venue: 'Kedarnath, Uttarakhand',
        price: 0,
        categories: ['Uttarakhand'],
        thumbnail_url: 'https://example.com/images/kedarnath-temple-thumb.jpg',
        medium_url: 'https://example.com/images/kedarnath-temple-med.jpg',
        latitude: '30.7352',
        longitude: '79.0669',
      },
      {
        id: '9',
        name: 'Konark Sun Temple',
        description: 'A UNESCO World Heritage Site dedicated to the Sun God Surya, located in Konark, Odisha, known for its intricate stone carvings and architecture.',
        host: 'Archaeological Survey of India',
        date: 'N/A',
        venue: 'Konark, Odisha',
        price: 0,
        categories: ['Odisha'],
        thumbnail_url: 'https://example.com/images/konark-sun-temple-thumb.jpg',
        medium_url: 'https://example.com/images/konark-sun-temple-med.jpg',
        latitude: '19.8876',
        longitude: '86.0983',
      },
      {
        id: '10',
        name: 'Badrinath Temple',
        description: 'A Hindu temple dedicated to Lord Vishnu, located in the Garhwal Himalayas of Uttarakhand, one of the Char Dham pilgrimage sites.',
        host: 'Badrinath Temple Committee',
        date: 'N/A',
        venue: 'Badrinath, Uttarakhand',
        price: 0,
        categories: ['Uttarakhand'],
        thumbnail_url: 'https://example.com/images/badrinath-temple-thumb.jpg',
        medium_url: 'https://example.com/images/badrinath-temple-med.jpg',
        latitude: '30.7437',
        longitude: '79.4932',
      },
      {
        id: '11',
        name: 'Guruvayur Temple',
        description: 'A Hindu temple dedicated to Lord Krishna, located in Guruvayur, Kerala, known for its grand festivals and traditions.',
        host: 'Guruvayur Devaswom',
        date: 'N/A',
        venue: 'Guruvayur, Kerala',
        price: 0,
        categories: ['Kerala'],
        thumbnail_url: 'https://example.com/images/guruvayur-temple-thumb.jpg',
        medium_url: 'https://example.com/images/guruvayur-temple-med.jpg',
        latitude: '10.5931',
        longitude: '76.0393',
      },
      {
        id: '12',
        name: 'Rameswaram Temple',
        description: 'A Hindu temple dedicated to Lord Shiva, located in Rameswaram, Tamil Nadu, known for its sacred water tanks and architectural splendor.',
        host: 'Ramanathaswamy Temple Committee',
        date: 'N/A',
        venue: 'Rameswaram, Tamil Nadu',
        price: 0,
        categories: ['Tamil Nadu'],
        thumbnail_url: 'https://example.com/images/rameswaram-temple-thumb.jpg',
        medium_url: 'https://example.com/images/rameswaram-temple-med.jpg',
        latitude: '9.2876',
        longitude: '79.3129',
      },
      {
        id: '13',
        name: 'Amarnath Temple',
        description: 'A Hindu temple dedicated to Lord Shiva, located in the Himalayas of Jammu and Kashmir, known for its annual pilgrimage to the Amarnath Cave.',
        host: 'Amarnath Shrine Board',
        date: 'N/A',
        venue: 'Amarnath, Jammu and Kashmir',
        price: 0,
        categories: ['Jammu and Kashmir'],
        thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Cave_Temple_of_Lord_Amarnath.jpg',
        medium_url: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Cave_Temple_of_Lord_Amarnath.jpg',
        latitude: '34.0704',
        longitude: '75.2927',
      },
      {
        id: '14',
        name: 'Dwarkadhish Temple',
        description: 'A Hindu temple dedicated to Lord Krishna, located in Dwarka, Gujarat, one of the Char Dham pilgrimage sites.',
        host: 'Dwarkadhish Temple Trust',
        date: 'N/A',
        venue: 'Dwarka, Gujarat',
        price: 0,
        categories: ['Gujarat'],
        thumbnail_url: 'https://example.com/images/dwarkadhish-temple-thumb.jpg',
        medium_url: 'https://example.com/images/dwarkadhish-temple-med.jpg',
        latitude: '22.2446',
        longitude: '68.9682',
      },
      {
        id: '15',
        name: 'Jyotirlinga Temple, Somanath',
        description: 'A Hindu temple dedicated to Lord Shiva, located in Prabhas Patan, Gujarat, one of the twelve Jyotirlinga shrines.',
        host: 'Shree Somnath Trust',
        date: 'N/A',
        venue: 'Prabhas Patan, Gujarat',
        price: 0,
        categories: ['Gujarat'],
        thumbnail_url: 'https://example.com/images/somanath-jyotirlinga-temple-thumb.jpg',
        medium_url: 'https://example.com/images/somanath-jyotirlinga-temple-med.jpg',
        latitude: '20.8829',
        longitude: '70.4055',
      },
      {
        id: '16',
        name: 'Kanaka Durga Temple',
        description: 'A Hindu temple dedicated to Goddess Kanaka Durga, located in Vijayawada, Andhra Pradesh, known for its annual Navaratri celebrations.',
        host: 'Kanaka Durga Temple Committee',
        date: 'N/A',
        venue: 'Vijayawada, Andhra Pradesh',
        price: 0,
        categories: ['Andhra Pradesh'],
        thumbnail_url: 'https://example.com/images/kanaka-durga-temple-thumb.jpg',
        medium_url: 'https://example.com/images/kanaka-durga-temple-med.jpg',
        latitude: '16.5135',
        longitude: '80.6561',
      },
      {
        id: '17',
        name: 'Kashi Vishwanath Temple',
        description: 'One of the most famous Hindu temples dedicated to Lord Shiva, located in Varanasi, Uttar Pradesh.',
        host: 'Kashi Vishwanath Temple Trust',
        date: 'N/A',
        venue: 'Varanasi, Uttar Pradesh',
        price: 0,
        categories: ['Uttar Pradesh'],
        thumbnail_url: 'https://example.com/images/kashi-vishwanath-temple-thumb.jpg',
        medium_url: 'https://example.com/images/kashi-vishwanath-temple-med.jpg',
        latitude: '25.3093',
        longitude: '83.0109',
      },
      {
        id: '18',
        name: 'Parshuram Kund',
        description: 'A sacred Hindu pilgrimage site associated with the sage Parshuram, located in the Lohit district of Arunachal Pradesh, known for its religious significance and annual festival.',
        host: 'Arunachal Pradesh Tourism Department',
        date: 'N/A',
        venue: 'Lohit, Arunachal Pradesh',
        price: 0,
        categories: ['Arunachal Pradesh'],
        thumbnail_url: 'https://example.com/images/parshuram-kund-thumb.jpg',
        medium_url: 'https://example.com/images/parshuram-kund-med.jpg',
        latitude: '27.8476',
        longitude: '96.2036',
      },
      
      {
        id: '19',
        name: 'Ganga Lake (Gyakar Sinyi)',
        description: 'A serene lake surrounded by lush forests, considered sacred by the local Monpa tribe and visited by pilgrims for spiritual rituals and offerings.',
        host: 'Arunachal Pradesh Tourism Department',
        date: 'N/A',
        venue: 'Itanagar, Arunachal Pradesh',
        price: 0,
        categories: ['Arunachal Pradesh'],
        thumbnail_url: 'https://example.com/images/ganga-lake-thumb.jpg',
        medium_url: 'https://example.com/images/ganga-lake-med.jpg',
        latitude: '27.0553',
        longitude: '93.9231',
      },
      
      {
        id: '20',
        name: 'Gompa Temple',
        description: 'A Buddhist temple located in the Tawang district of Arunachal Pradesh, known for its colorful architecture, prayer flags, and serene atmosphere.',
        host: 'Tawang Monastery Administration',
        date: 'N/A',
        venue: 'Tawang, Arunachal Pradesh',
        price: 0,
        categories: ['Arunachal Pradesh'],
        thumbnail_url: 'https://example.com/images/gompa-temple-thumb.jpg',
        medium_url: 'https://example.com/images/gompa-temple-med.jpg',
        latitude: '27.5946',
        longitude: '91.8651',
      },
      
      {
        id: '21',
        name: 'Bomdila Monastery',
        description: 'A Buddhist monastery located in Bomdila, Arunachal Pradesh, known for its stunning views of the Himalayas and serene ambiance for meditation and prayers.',
        host: 'Bomdila Monastery Administration',
        date: 'N/A',
        venue: 'Bomdila, Arunachal Pradesh',
        price: 0,
        categories: ['Arunachal Pradesh'],
        thumbnail_url: 'https://example.com/images/bomdila-monastery-thumb.jpg',
        medium_url: 'https://example.com/images/bomdila-monastery-med.jpg',
        latitude: '27.2594',
        longitude: '92.4166',
      },
      {
        id: '210',
        name: 'Kamakhya Temple',
        description: 'A Hindu temple dedicated to Goddess Kamakhya, situated atop the Nilachal Hill in Guwahati, Assam, known for its annual Ambubachi Mela and Tantric rituals.',
        host: 'Kamakhya Temple Management Committee',
        date: 'N/A',
        venue: 'Guwahati, Assam',
        price: 0,
        categories: ['Assam'],
        thumbnail_url: 'https://example.com/images/kamakhya-temple-thumb.jpg',
        medium_url: 'https://example.com/images/kamakhya-temple-med.jpg',
        latitude: '26.1584',
        longitude: '91.7695',
      },
      
      {
        id: '22',
        name: 'Navagraha Temple',
        description: 'A Hindu temple dedicated to the nine celestial bodies (Navagrahas), located on Chitrasal Hill in Guwahati, Assam, known for astrological significance and rituals.',
        host: 'Assam Navagraha Temple Management Committee',
        date: 'N/A',
        venue: 'Guwahati, Assam',
        price: 0,
        categories: ['Assam'],
        thumbnail_url: 'https://example.com/images/navagraha-temple-thumb.jpg',
        medium_url: 'https://example.com/images/navagraha-temple-med.jpg',
        latitude: '26.1775',
        longitude: '91.7703',
      },
      
      {
        id: '23',
        name: 'Umananda Temple',
        description: 'A Shiva temple located on the Peacock Island in the middle of the Brahmaputra River, near Guwahati, Assam, known for its scenic beauty and religious significance.',
        host: 'Umananda Temple Trust',
        date: 'N/A',
        venue: 'Peacock Island, Assam',
        price: 0,
        categories: ['Assam'],
        thumbnail_url: 'https://example.com/images/umananda-temple-thumb.jpg',
        medium_url: 'https://example.com/images/umananda-temple-med.jpg',
        latitude: '26.1453',
        longitude: '91.7649',
      },
      
      {
        id: '24',
        name: 'Basistha Temple',
        description: 'A Hindu shrine dedicated to sage Vashishtha, located in the Basistha Ashram area of Guwahati, Assam, known for its serene environment and natural springs.',
        host: 'Basistha Temple Management Committee',
        date: 'N/A',
        venue: 'Guwahati, Assam',
        price: 0,
        categories: ['Assam'],
        thumbnail_url: 'https://example.com/images/basistha-temple-thumb.jpg',
        medium_url: 'https://example.com/images/basistha-temple-med.jpg',
        latitude: '26.1181',
        longitude: '91.7703',
      },
      
      {
        id: '25',
        name: 'Hayagriva Madhava Temple',
        description: 'A Vaishnavite temple dedicated to Lord Vishnu, located in Hajo, Assam, known for its ancient history and connection to the Hayagriva Madhava legend.',
        host: 'Hayagriva Madhava Temple Trust',
        date: 'N/A',
        venue: 'Hajo, Assam',
        price: 0,
        categories: ['Assam'],
        thumbnail_url: 'https://example.com/images/hayagriva-madhava-temple-thumb.jpg',
        medium_url: 'https://example.com/images/hayagriva-madhava-temple-med.jpg',
        latitude: '26.2135',
        longitude: '91.5785',
      },
      {
        id: '26',
        name: 'Mahabodhi Temple',
        description: 'A UNESCO World Heritage Site and Buddhist temple located in Bodh Gaya, Bihar, marking the site where Gautama Buddha is said to have attained enlightenment.',
        host: 'Mahabodhi Temple Management Committee',
        date: 'N/A',
        venue: 'Bodh Gaya, Bihar',
        price: 0,
        categories: ['Bihar'],
        thumbnail_url: 'https://example.com/images/mahabodhi-temple-thumb.jpg',
        medium_url: 'https://example.com/images/mahabodhi-temple-med.jpg',
        latitude: '24.6955',
        longitude: '84.9915',
      },
      
      {
        id: '27',
        name: 'Vishnupad Temple',
        description: 'A Hindu temple dedicated to Lord Vishnu, located in Gaya, Bihar, known for its sacred footprint of Lord Vishnu and its connection to Hindu mythology.',
        host: 'Vishnupad Temple Trust',
        date: 'N/A',
        venue: 'Gaya, Bihar',
        price: 0,
        categories: ['Bihar'],
        thumbnail_url: 'https://example.com/images/vishnupad-temple-thumb.jpg',
        medium_url: 'https://example.com/images/vishnupad-temple-med.jpg',
        latitude: '24.7875',
        longitude: '85.0033',
      },
      
      {
        id: '28',
        name: 'Tara Mandir',
        description: 'A Buddhist temple located in Tarapur, Bihar, dedicated to Goddess Tara, known for its ancient architecture and spiritual ambiance.',
        host: 'Tara Mandir Management Committee',
        date: 'N/A',
        venue: 'Tarapur, Bihar',
        price: 0,
        categories: ['Bihar'],
        thumbnail_url: 'https://example.com/images/tara-mandir-thumb.jpg',
        medium_url: 'https://example.com/images/tara-mandir-med.jpg',
        latitude: '24.9411',
        longitude: '85.7816',
      },
      {
        id: '29',
        name: 'Pawapuri Jalmandir',
        description: 'A Jain temple located in Pawapuri, Bihar, marking the cremation site of Lord Mahavira, known for its serene surroundings and sacred pond.',
        host: 'Pawapuri Jalmandir Trust',
        date: 'N/A',
        venue: 'Pawapuri, Bihar',
        price: 0,
        categories: ['Bihar'],
        thumbnail_url: 'https://example.com/images/pawapuri-jalmandir-thumb.jpg',
        medium_url: 'https://example.com/images/pawapuri-jalmandir-med.jpg',
        latitude: '25.7285',
        longitude: '85.4979',
      },
      
      {
        id: '30',
        name: 'Mangla Gauri Temple',
        description: 'A Hindu temple dedicated to Goddess Parvati, located in Gaya, Bihar, known for its ancient history and connection to Hindu mythology.',
        host: 'Mangla Gauri Temple Trust',
        date: 'N/A',
        venue: 'Gaya, Bihar',
        price: 0,
        categories: ['Bihar'],
        thumbnail_url: 'https://example.com/images/mangla-gauri-temple-thumb.jpg',
        medium_url: 'https://example.com/images/mangla-gauri-temple-med.jpg',
        latitude: '24.7953',
        longitude: '84.9991',
      }
      
      
      
      
  
      
  ];
  